### PR TITLE
Upgrade WP Sage Core Commenting - Part One - Sorting #5

### PR DESCRIPTION
**Pull request by coakenfold**
Note
------------------------

I created a wordpress plugin and put it inside:
  /citizen-engagement-web-toolkit/code/bcgov-comment-theme/lib/custom/co-mment-sort

It will need to be activated in wordpress in the usual manner. I created a symlink in my local wp-content/plugins and that worked well for me.

========================================================================

Paypal email link
------------------------

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=F2E6H8EUKWXX8

========================================================================

Copy of Terms
------------------------

Pay for Pull Terms

Please note: you are required to complete the information requested at the end of this document and submit the modified version of this document with each Opportunity. Refer to "Introduction" and "Acceptance", below.

Introduction

These Pay for Pull Terms ("Terms") govern Developers and Issuers that participate in the BC Developers' Exchange, specifically in Pay for Pull Opportunities. Pay for Pull Opportunities are designed to enable Issuers to obtain and pay for Contributions to digital resources from Developers in a relatively quick and straightforward way. It is a mechanism to invite Developers to work on a simple but technical task, with the potential to receive a Payment in accordance with the Opportunity and the Acceptance Criteria.

To be considered for a Pay for Pull Opportunity, the Developer must:

a)indicate acceptance of the Terms by completing the information requested at the end of the Terms, below; and b)submit the Accepted Terms with each Pull Request.

Definitions

Throughout the Terms, the following definitions apply:

" Acceptance Criteria" means the requirements and specifications necessary for a Pull Request to be considered, reviewed and potentially accepted for a Payment;

" Accepted Terms" means the Terms as agreed to by the Developer, with the information completed as required at the end of the Terms, below, and submitted to the Issuer with the Pull Request;

" BC Developers' Exchange" means the BC Developers' Exchange Web site located at www.bcdevexchange.org, and any services associated with the BC Developers' Exchange;

" Contribution" means the work, such as source code, offered by a Developer in a Pull Request;

" Developer" means a person or entity with the legal capacity to contract that submits a Pull Request in response to a Pay for Pull Opportunity;

" Issuer" means the Province or a Public Sector Entity, as applicable;

" License" means the terms and conditions regarding the use, modification and sharing of the content in a Repository;

" Licensing File" means the file in the Repository that contains the License attached to the Pay for Pull Opportunity;

" Opportunity Contact" means the individual named in a Pay for Pull Opportunity as the contact person for the Issuer;

" Pay for Pull Opportunity" or " Opportunity" means the issue tagged with the 'rapid adoption' label within a Repository, and includes any attached or referenced appendices, addenda, schedules or exhibits;

" Payment" means the value of remuneration associated with the Pay for Pull Opportunity;

" Province" means the Government of British Columbia;

" Public Sector Entity" means a public sector entity in British Columbia;

" Pull Request" means the submission of a Contribution from a Developer;

" Repository" or " Repo" means the location on GitHub where the Pay for Pull Opportunity is posted and stored; and

" Submission Period" means the period stated in the Pay for Pull Opportunity during which time Developers may submit a Pull Request, starting from the issuance of the Opportunity and ending on (a) the end date stated in the Opportunity or (b) when the Opportunity is earlier closed by the Issuer.

Agreeing to the Terms

1.By submitting a Pull Request and the Accepted Terms, the Developer confirms that the Developer has read and agrees with the Terms.

Information about a Pay for Pull Opportunity

2.The issue forming the Pay for Pull Opportunity will be described, and will include criteria defining what a Pull Request must contain/accomplish and the Acceptance Criteria.

3.Any revisions to the Pay for Pull Opportunity will also be posted on GitHub. If the Opportunity is modified in any way or cancelled, notification will be provided on GitHub. It is entirely a Developer's responsibility to check GitHub for information about the Pay for Pull Opportunity.

4.The Issuer is not obligated to make a Payment to any Developer.

5.The Issuer has the right to modify a Pay for Pull Opportunity at any time prior to the end of the Submission Period, including the right to cancel the Pay for Pull Opportunity at any time prior to making a Payment.

Submitting a Pull Request

6.A Developer may:

c)submit more than one Pull Request in response to a Pay for Pull Opportunity; and d)withdraw a Pull Request at any time before the Issuer makes a Payment.

7.Any Pull Requests submitted by the Developer will be considered according to the Pull Request time stamp applied by GitHub.

Developers' Responsibilities

8.In order to be eligible for Payment in relation to a Pay for Pull Opportunity, the Developer must include in its Pull Request the payment information prescribed in the Pay for Pull Opportunity in a form satisfactory to the Issuer.

9.Developers will retain the copyright to the Contribution submitted in their Pull Request unless the License file issued with the Pay for Pull Opportunity indicates otherwise. By submitting a Pull Request, Developers agree to grant the Issuer of the applicable Pay for Pull Opportunity rights in accordance with the License applicable to that Pay for Pull Opportunity.

10.Developers must ensure there is no conflict of interest, either real or perceived in respect of a Pay for Pull Opportunity. If a Developer is in doubt as to whether there might be a conflict of interest, the Developer should consult with the Opportunity Contact prior to submitting a Pull Request.

11.Developers are responsible for:

a)ensuring their Pull Requests are complete and are in compliance with the Pay for Pull Opportunity and these Terms; b)their own expenses in participating in a Pay for Pull Opportunity, including any costs in preparing a Pull Request; c)accepting and complying with the terms of use of sites used in conjunction with a Pay for Pull Opportunity (e.g. GitHub, PayPal); d)ensuring they have the ability and authority to submit a Pull Request and accept these Terms applicable to the Pay for Pull Opportunity; e)determining, managing and paying any income or other taxes, fees or applicable payments that may be incurred as a result of a Payment; and f)complying with all applicable laws in relation to the submission of a Pull Request and receipt of a Payment.

Representations and Warranties

12.Developers represent and warrant that:

a) the material contained in the Pull Request does not infringe, misappropriate or misuse any copyright, patent, trade-mark, trade secret or confidential or proprietary information of a third party;

b) they have the rights to submit the material contained in their Pull Request;

c) they are not aware of any circumstances that would give rise to a conflict of interest, either actual or perceived in respect of the Pay for Pull Opportunity; and

d) that at the date the Pull Request is submitted they have the power and capacity to enter into this Agreement and, if the Developer is not an individual, to observe, perform and comply with the terms of this Agreement and all necessary corporate or other proceedings have been taken and done to authorize the execution and delivery of this Agreement by, or on behalf of, the Developer.

Evaluation of Pull Requests

13.Pull Requests will be reviewed and assessed:

a)in the order they are received, according to the time stamp indicated on the request on GitHub; and b)in accordance with the Acceptance Criteria described in the Pay for Pull Opportunity.

14.The first Pull Request received that meets the Acceptance Criteria described in the Pay for Pull Opportunity and is merged into the master branch will receive Payment. If the Pay for Pull Opportunity indicates that more than one Payment may be made, Pull Requests will continue to be evaluated in the order they are received and additional Payment may be made until the end of the Submission Period.

15.The Issuer reserves the right in its sole discretion to:

a)waive any non-material irregularity, defect or deficiency in a Pull Request; b)request clarifications from a Developer with respect to its Pull Request, without any obligation to make such a request to all Developers, and consider such clarifications in evaluating the Pull Request; c)reject any Pull Request containing inaccurate or incomplete payment information; and d)reject any Pull Request that is not submitted with Accepted Terms.

Payment

16.The value of the Payment offered in the Pay for Pull Opportunity is a fixed amount in Canadian dollars and is not negotiable.

17.Acceptance of the Pull Request by the Issuer and merging the Contribution into the master branch will result in a Payment being made as specified in the Pay for Pull Opportunity within 30 days.

18.If the Issuer is the Province, the Issuer's obligation to pay money to the Developer is subject to the Financial Administration Act, which makes that obligation subject to an appropriation being available in the fiscal year of the Issuer during which payment becomes due.

Limitation of Liability

19.Under no circumstances will the Issuer or any of its respective servants, employees or agents be liable to any person or business entity for any direct, indirect, special, incidental, consequential or other damages based on any Developer's submission of a Pull Request in response to a Pay for Pull Opportunity.

Indemnity

20.Developers agree to indemnify and save harmless the Issuer or any of its respective employees or agents from and against all claims, demands, obligations, losses, liabilities, costs, debts and expenses, including reasonable legal fees and any claim of infringement of third-party intellectual property rights, that the Issuer or any of the Issuer's employees or agents may sustain, incur, suffer or be put to at any time, either before or after this Agreement ends (each a "Loss") to the extent the Loss is directly or indirectly caused or contributed to by any act or omission by the Developer or by any of the Developer's agents, employees, officers, directors or subcontractors in connection with this Agreement.

General

21.The Terms will not in any way make the Developer an employee, agent or independent contractor of the Issuer.

22.If any term or provision of the Terms is invalid, illegal or unenforceable, all other terms and provisions will nonetheless remain in full force and effect.

23.The Issuer has no further obligations or commitments to any Developer beyond those stated in the Terms.

24.Developers agree that the Terms are governed by and will be construed in accordance with the laws of British Columbia.

25.Developers agree that any action at law or in equity in any way arising from the Terms and/or in any way associated with the use of the Site will be resolved by arbitration under the Arbitration Act (British Columbia) and that the place of arbitration will be Victoria, British Columbia.

Acceptance

To indicate acceptance of the Terms, the Developer will complete the information below and submit the Accepted Terms, in full, with the applicable Pull Request.

A. Legal Name of Developer (person or entity): Chad Oakenfold

B. Legal Name of Person Submitting Pull Request on behalf of Developer (if different from "A"):

C: Email Address for Developer's PayPal Account: chad@oakenfold.ca

### CODE REVIEW

**Comment by SteveMHoward** [comment]
@coakenfold 

Thanks for your submission! We will review this over the next week and let you know if it has been accepted.

**Comment by SteveMHoward** [comment]
@coakenfold 

Thanks again for your submission! This is very well coded and easy to navigate through. 

There are a couple of things that need to be fixed though:
- When we activate the plugin we get a PHP error. In co-mment-sort/includes/class-co-mment-sort-walker.php the start_el function should have a 5th argument ($current_object_id = 0): https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-includes/class-wp-walker.php#L95
- In the issue thread you asked us how you should sort when you have an older parent with the newest comment. We responded (https://github.com/bcgov/citizen-engagement-web-toolkit/issues/5#issuecomment-176866671) asking that the sort by date function refers to the date of the parent instead of the children, but in our testing it is not sorting this way. An older parent with the newest child comment is coming up before a newer parent when sorting by date.

This is very close though and is definitely what we are looking for! Please fix these two items and submit another pull request.

**Comment by coakenfold** [comment]
Thanks for the feedback.

1) I'll add the 5th argument but I hadn't encountered that issue on my localhost. What version of Wordpress are you running? Hopefully I can reproduce on my side to ensure the fix works.

2) Ah ok, apparently I misread the response. I'm sorting by the newest comment in the thread (considering root & children) and it's easy to fix. 

Though it strikes me that sorting by the newest comment in the entire thread would be more useful since a new comment under an old parent could be buried. 

Just to be clear, this is the desired sorting...
Before ASC
----
- Parent Comment @ Jan 1
  - Child Comment @ Feb 10
- Parent Comment @ Feb 1
- Parent Comment @ Feb 2
 - Child Comment @ Feb 10

After DESC
---
- Parent Comment @ Feb 2
 - Child Comment @ Feb 10
- Parent Comment @ Feb 1
- Parent Comment @ Jan 1
  - Child Comment @ Feb 10

And not this type of DESC
---
- Parent Comment @ Feb 2
 - Child Comment @ Feb 10
- Parent Comment @ Jan 1
  - Child Comment @ Feb 10
- Parent Comment @ Feb 1

**Comment by SteveMHoward** [comment]
@coakenfold 

1. I am testing in 4.4.2 in a very verbose test environment, but I looked back at older versions of the Walker class and it seems that the 5th argument has been needed for at least all of 4.x. Adding the default $current_object_id = 0 gets rid of the PHP errors and the sorting works as expected.
2. Yes, your example of desired sorting is correct. We have had scenarios in the past where an older comment with a long reply chain has kind of drowned out new top-level comments, so that is why we have requested sorting in this way.

Of course, after user testing we may discover that most people agree with you and want the newest child comment on top, or a new sorting function for most recent reply, but fortunately that is out of scope for this issue.

**Comment by coakenfold** [comment]
Ok, I turned on the debugging and saw similar issues logged to debug.log. I updated the new PR #14 to include the default value of $current_object_id and it's no longer cropping up.

I just commented out the children date part of the function so it'll be trivial to re-instate if desired.

**Pull request closed without merging**
